### ISSUE TITLE
Config Errors While Starting Biomedicus Deploy

### ISSUE THREAD

**Issue by DaveJohnson8080** [nlpie/biomedicus#102]
**Describe the bug**
Unable to start biomedicus via "biomedicus deploy" due to configuration errors.

**To Reproduce**
biomedicus deploy --config biomedicus_deploy_config.yml'
(config file created from "biomedicus write-config deploy")

**Expected behavior**
biomedicus processors start etc.

**Terminal Output**
`INFO:biomedicus.deployment.deploy_biomedicus:Data folder is up to date version 3.0b9
Traceback (most recent call last):
  File "/home/dave/sandboxes/biomedicus3-docker/biomedicusrc3/bin/biomedicus", line 8, in <module>
    sys.exit(main())
  File "/home/dave/sandboxes/biomedicus3-docker/biomedicusrc3/lib/python3.6/site-packages/biomedicus/cli.py", line 117, in main
    f(conf)
  File "/home/dave/sandboxes/biomedicus3-docker/biomedicusrc3/lib/python3.6/site-packages/biomedicus/deployment/deploy_biomedicus.py", line 111, in deploy
    deployment = Deployment.from_yaml_file(conf.config)
  File "/home/dave/sandboxes/biomedicus3-docker/biomedicusrc3/lib/python3.6/site-packages/mtap/deployment.py", line 512, in from_yaml_file
    return Deployment.load_configuration(conf)
  File "/home/dave/sandboxes/biomedicus3-docker/biomedicusrc3/lib/python3.6/site-packages/mtap/deployment.py", line 490, in load_configuration
    processors = [ProcessorDeployment.from_conf(c) for c in processors_list]
  File "/home/dave/sandboxes/biomedicus3-docker/biomedicusrc3/lib/python3.6/site-packages/mtap/deployment.py", line 490, in <listcomp>
    processors = [ProcessorDeployment.from_conf(c) for c in processors_list]
  File "/home/dave/sandboxes/biomedicus3-docker/biomedicusrc3/lib/python3.6/site-packages/mtap/deployment.py", line 388, in from_conf
    entry_point=conf['entryPoint'],
KeyError: 'entryPoint'
`

`INFO:biomedicus.deployment.deploy_biomedicus:Data folder is up to date version 3.0b9
Traceback (most recent call last):
  File "/home/dave/sandboxes/biomedicus3-docker/biomedicusrc3/bin/biomedicus", line 8, in <module>
    sys.exit(main())
  File "/home/dave/sandboxes/biomedicus3-docker/biomedicusrc3/lib/python3.6/site-packages/biomedicus/cli.py", line 117, in main
    f(conf)
  File "/home/dave/sandboxes/biomedicus3-docker/biomedicusrc3/lib/python3.6/site-packages/biomedicus/deployment/deploy_biomedicus.py", line 112, in deploy
    attach_biomedicus_jar(deployment, conf.jvm_classpath)
  File "/home/dave/sandboxes/biomedicus3-docker/biomedicusrc3/lib/python3.6/site-packages/biomedicus/deployment/deploy_biomedicus.py", line 98, in attach_biomedicus_jar
    classpath = deployment.shared_processor_config.java_classpath
AttributeError: 'SharedProcessorConfig' object has no attribute 'java_classpath'
[biomedicus_deploy_config.yml.txt](https://github.com/nlpie/biomedicus3/files/7855878/biomedicus_deploy_config.yml.txt)
`

**Environment**
OS:[e.g. Ubuntu 18.04
Version: 3.0rc0
Python Version 3.6.9
Java Version OpenJDK 11

**Additional context**
None

**Comment by benknoll-umn** [comment]
I just tagged and pushed a release to pypi which should resolve this issue.

**Comment by DaveJohnson8080** [comment]
Runs ok now. Thanks!
