### ISSUE TITLE
NullPointerException while processing biomedicus-tnt-tagger for document

### ISSUE THREAD

**Issue by DaveJohnson8080** [nlpie/biomedicus#103]
[test-summary.txt](https://github.com/nlpie/biomedicus3/files/7864660/test-summary.txt)
**Describe the bug**
NullPointerException while processing biomedicus-tnt-tagger for document.

**To Reproduce**
Run pipeline for attached document (test-summary.txt). Can limit to just the biomedicus-sentences and biomedicus-tnt-tagger processors.

**Expected behavior**
Successful tagger result.

**Terminal Output**
Result summary from biomedicus_sentences:
`{{ "timingInfo": { "process_method": "0.032712s" }, "createdIndices": [ { "documentName": "test-summary.txt", "indexName": "sentences" } ] }}`

tagger terminal output:
`11:07:10.613 [pool-4-thread-2] ERROR edu.umn.nlpie.mtap.processing.DefaultProcessorService - Exception during processing of event '23dff036-a06b-4b99-877c-310d9b80fffb'
java.lang.NullPointerException: null
	at edu.umn.nlpie.mtap.model.Event$Builder.build(Event.java:545) ~[biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at edu.umn.nlpie.mtap.processing.LocalProcessorRunner.process(LocalProcessorRunner.java:53) ~[biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at edu.umn.nlpie.mtap.processing.DefaultProcessorService.process(DefaultProcessorService.java:93) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at edu.umn.nlpie.mtap.api.v1.ProcessorGrpc$MethodHandlers.invoke(ProcessorGrpc.java:398) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:797) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]`

**Environment**
OS: Ubuntu 18.04
Version: 3.0rc1
Python Version 3.6.9
Java Version OpenJDK 11

**Additional context**
None

**Comment by benknoll-umn** [comment]
I'm unable to replicate using the default pipeline. Are you using custom pipeline grpc calls or event creation logic?

This is being caused by the code block during instantiation of the local proxy object for the event:

```java
if (clientPool != null) {
        if (eventInstanceID != null) {
          client = clientPool.instanceFor(eventInstanceID);
        } else {
          client = clientPool.nextInstance();
          eventInstanceID = client.getInstanceId();
        }
        client.openEvent(eventID, onlyCreateNew); // This is the line that's throwing the NPE.
 }
```

What I think may be happening is that "eventInstanceId" is an empty string, the default value provided by grpc when a field is not specified.

One of the changes recently was the addition of client-side load balancing via an event service pool. This means there are now two parts to event identification: the existing event_id and an event_service_instance_id which maps it to a specific event service. The event_service_instance_id is provided by the GetEventsInstanceId on the events server and the ProcessRequest call on the processor server has been updated to include an event_service_instance_id field. The new logic is as follows:
1. Pipeline / Client picks an event service via round-robin from available services.
2. Event is created using that service.
3. Event is identified in two parts: event_id and event_service_instance_id
4. Process called on processor using two identifiers
5. Processor retrieves appropriate event service from a map of service ids to event services (provided via list of addresses at processor launch), and uses that service to interact with the event.

I can look into adding a fail-safe fallback for when there's no event_instance_id and only one event service available. It would be something like:
```
if (clientPool != null) {
        if (eventInstanceID != null) {
          client = clientPool.instanceFor(eventInstanceID);
        } else {
          client = clientPool.nextInstance();
          eventInstanceID = client.getInstanceId();
        }
        if (client == null) {
           if ((eventInstanceId == null || eventInstanceId.isEmpty()) && clientPool.size() == 1) {
              client = clientPool.nextInstance();
           } else {
               // more informative log message about missing instance id. Fail out.
           }
        }
        client.openEvent(eventID, onlyCreateNew);
 }
```

**Comment by DaveJohnson8080** [comment]
I updated my code (grpc custom pipeline) to account for the instance ID. Everything is working ok now.

Thanks for the info. I like that load balancing strategy.

Do you think I would be better off creating a single python pipeline processor and call that from my code instead of having the entire pipeline procedure in my own code?

**Comment by benknoll-umn** [comment]
We added a pipeline runner tool that runs a configurable pipeline from a yml file, we're in the process of fully documenting it and will have tutorials on using the pipeline configuration and also on customizing the data source within a couple weeks.

**Comment by DaveJohnson8080** [comment]
That sounds great. Thanks!
