### ISSUE TITLE
Corpus of problematic RTF documents

### ISSUE THREAD

**Issue by rmcewan** [nlpie/biomedicus#108]
**Describe the bug**
A set of ~1.26M RTF documents was run through the `biomedicus run-rtf-to-text --max-failures 100` and resulted in ~80 docs that failed for one reason or another to produce this corpus of problematic RTF documents. 

**To Reproduce**
Run `biomedicus run-rtf-to-text --max-failures 100` on the 80 docs located at `hermes:/data/problematic_rtf_docs`

**Expected behavior**
All docs should fail for one reason or another

**Terminal Output**
Example output
```
01:18:27.799 [pool-4-thread-6] ERROR edu.umn.nlpie.mtap.processing.DefaultProcessorService - Exception during processing of event '1148281491-1050341492.rtf'
java.lang.IllegalStateException: java.nio.charset.UnmappableCharacterException: Input length = 1
	at edu.umn.biomedicus.rtf.RtfProcessor.process(RtfProcessor.java:115) ~[biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at edu.umn.nlpie.mtap.processing.LocalProcessorRunner.process(LocalProcessorRunner.java:57) ~[biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at edu.umn.nlpie.mtap.processing.DefaultProcessorService.process(DefaultProcessorService.java:93) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at edu.umn.nlpie.mtap.api.v1.ProcessorGrpc$MethodHandlers.invoke(ProcessorGrpc.java:398) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:797) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.nio.charset.UnmappableCharacterException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:275) ~[?:?]
	at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:815) ~[?:?]
	at edu.umn.biomedicus.rtf.beans.keywords.HexKeywordAction.executeAction(HexKeywordAction.java:55) ~[biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at edu.umn.biomedicus.rtf.reader.RtfParser.parseRtf(RtfParser.java:89) ~[biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at edu.umn.biomedicus.rtf.RtfProcessor.process(RtfProcessor.java:105) ~[biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	... 11 more
01:29:26.033 [pool-4-thread-5] ERROR edu.umn.nlpie.mtap.processing.DefaultProcessorService - Exception during processing of event '1363641824-1281141601.rtf'
java.lang.IllegalStateException: edu.umn.biomedicus.rtf.exc.EndOfFileException
	at edu.umn.biomedicus.rtf.RtfProcessor.process(RtfProcessor.java:115) ~[biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at edu.umn.nlpie.mtap.processing.LocalProcessorRunner.process(LocalProcessorRunner.java:57) ~[biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at edu.umn.nlpie.mtap.processing.DefaultProcessorService.process(DefaultProcessorService.java:93) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at edu.umn.nlpie.mtap.api.v1.ProcessorGrpc$MethodHandlers.invoke(ProcessorGrpc.java:398) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:797) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: edu.umn.biomedicus.rtf.exc.EndOfFileException
	at edu.umn.biomedicus.rtf.reader.RtfParser.parseKeyword(RtfParser.java:121) ~[biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at edu.umn.biomedicus.rtf.reader.RtfParser.parseRtf(RtfParser.java:82) ~[biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at edu.umn.biomedicus.rtf.RtfProcessor.process(RtfProcessor.java:105) ~[biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	... 11 more
01:33:44.375 [pool-4-thread-6] ERROR edu.umn.nlpie.mtap.processing.DefaultProcessorService - Exception during processing of event '226220910-215588560.rtf'
java.lang.IllegalStateException: edu.umn.biomedicus.rtf.exc.EndOfFileException
	at edu.umn.biomedicus.rtf.RtfProcessor.process(RtfProcessor.java:115) ~[biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at edu.umn.nlpie.mtap.processing.LocalProcessorRunner.process(LocalProcessorRunner.java:57) ~[biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at edu.umn.nlpie.mtap.processing.DefaultProcessorService.process(DefaultProcessorService.java:93) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at edu.umn.nlpie.mtap.api.v1.ProcessorGrpc$MethodHandlers.invoke(ProcessorGrpc.java:398) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:797) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: edu.umn.biomedicus.rtf.exc.EndOfFileException
	at edu.umn.biomedicus.rtf.reader.RtfParser.parseKeyword(RtfParser.java:121) ~[biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at edu.umn.biomedicus.rtf.reader.RtfParser.parseRtf(RtfParser.java:82) ~[biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	at edu.umn.biomedicus.rtf.RtfProcessor.process(RtfProcessor.java:105) ~[biomedicus-all.jar:task ':shadowJar' property 'archiveVersion']
	... 11 more
```

**Environment**
 - OS: Red Hat Enterprise Linux Server release 7.9 (Maipo)
 - Python 3.6.8
 - OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.1+12)

**Additional context**
B9 install used to process the docs can be found in `hermes:/opt/b9v3_rtf`

**Comment by benknoll-umn** [comment]
Resolved by #111
