### ISSUE TITLE
Unable to download data [SSL: CERTIFICATE_VERIFY_FAILED] 

### ISSUE THREAD

**Issue by polkhovsky** [nlpie/biomedicus#69]
I followed instructions to install biomedicus v3 on both my Mac and a clean Ubuntu VM. Both produced the same error below. I tried every suggestion I found online:

- pip3 install certifi
- running Install Certificates.command in Mac
- running Update Shell Profile.command

Nothing seems to help.

`alex@labrat:~$ biomedicus deploy --download-data
No existing data folder.
Starting download:  https://nlpie.umn.edu/downloads/open/biomedicus-3.0b6-standard-data.zip
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1326, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1006, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 946, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1409, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alex/.local/bin/biomedicus", line 8, in <module>
    sys.exit(main())
  File "/home/alex/.local/lib/python3.8/site-packages/biomedicus/cli.py", line 77, in main
    f(conf)
  File "/home/alex/.local/lib/python3.8/site-packages/biomedicus/deployment/deploy_biomedicus.py", line 101, in deploy
    check_data(conf.download_data)
  File "/home/alex/.local/lib/python3.8/site-packages/biomedicus/deployment/deploy_biomedicus.py", line 71, in check_data
    download_data_to(download_url, data)
  File "/home/alex/.local/lib/python3.8/site-packages/biomedicus/deployment/deploy_biomedicus.py", line 86, in download_data_to
    urllib.request.urlretrieve(download_url, filename=temporary_file.name,
  File "/usr/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1369, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1329, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>
alex@labrat:~$
`

**Comment by benknoll-umn** [comment]
Hello, as a manual workaround could you try downloading that linked file (https://nlpie.umn.edu/downloads/open/biomedicus-3.0b6-standard-data.zip) and unzipping the contents to ~/.biomedicus/data. I'll work on replicating and debugging this.

**Comment by polkhovsky** [comment]
Yes, that was indeed the workaround I came to last night. I had to manually update the file name to b6 because it wasn’t listed on the downloads page. 

I appreciate the response!
