### ISSUE TITLE
Processor "biomedicus-selective-dependencies" failed 

### ISSUE THREAD

**Issue by polkhovsky** [nlpie/biomedicus#70]
**Describe the bug**
While running a batch of files through the pipeline, the error occurred. This happens sporadically. The file on which the process fails may process normally next time the same batch of files is processed. 
More information: using multiple threads seems to be the problem. I've been running batches of 100 files using a single thread  `biomedicus run --threads 1 /input /output` with no issues.  As soon as I set threads to anything but 1 the process will consistently fail. 

**To Reproduce**
biomedicus run /input_folder /output_folder

**Terminal Output**

```

13:14:01.162 [main] INFO  edu.umn.nlpie.mtap.processing.DefaultProcessorService - Server for processor_id: biomedicus-section-headers started on port: 10109
Done starting all processors
Processor "biomedicus-selective-dependencies" failed while processing event with id: 46-10.txt
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mtap/processing/_runners.py", line 85, in call_process
    result = self.processor.process(event, p)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mtap/processing/base.py", line 296, in process
    return self.process_document(document, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/biomedicus/dependencies/stanza_selective_parser.py", line 91, in process_document
    stanza_doc = self.nlp([sentence.text])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stanza/pipeline/core.py", line 166, in __call__
    doc = self.process(doc)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stanza/pipeline/core.py", line 160, in process
    doc = self.processors[processor_name].process(doc)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stanza/pipeline/lemma_processor.py", line 67, in process
    ps, es = self.trainer.predict(b, self.config['beam_size'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stanza/models/lemma/trainer.py", line 91, in predict
    preds, edit_logits = self.model.predict(src, src_mask, pos=pos, beam_size=beam_size)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stanza/models/common/seq2seq_model.py", line 214, in predict
    return self.predict_greedy(src, src_mask, pos=pos)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stanza/models/common/seq2seq_model.py", line 179, in predict_greedy
    h_in, (hn, cn) = self.encode(enc_inputs, src_lens)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stanza/models/common/seq2seq_model.py", line 119, in encode
    packed_h_in, (hn, cn) = self.encoder(packed_inputs, (self.h0, self.c0))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 574, in forward
    self.check_forward_args(input, hx, batch_sizes)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 528, in check_forward_args
    self.check_hidden_size(hidden[0], expected_hidden_size,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 195, in check_hidden_size
    raise RuntimeError(msg.format(expected_hidden_size, tuple(hx.size())))
RuntimeError: Expected hidden[0] size (2, 5, 100), got (2, 7, 100)

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mtap/processing/_runners.py", line 85, in call_process
    result = self.processor.process(event, p)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mtap/processing/base.py", line 296, in process
    return self.process_document(document, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/biomedicus/dependencies/stanza_selective_parser.py", line 91, in process_document
    stanza_doc = self.nlp([sentence.text])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stanza/pipeline/core.py", line 166, in __call__
    doc = self.process(doc)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stanza/pipeline/core.py", line 160, in process
    doc = self.processors[processor_name].process(doc)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stanza/pipeline/lemma_processor.py", line 67, in process
    ps, es = self.trainer.predict(b, self.config['beam_size'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stanza/models/lemma/trainer.py", line 91, in predict
    preds, edit_logits = self.model.predict(src, src_mask, pos=pos, beam_size=beam_size)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stanza/models/common/seq2seq_model.py", line 214, in predict
    return self.predict_greedy(src, src_mask, pos=pos)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stanza/models/common/seq2seq_model.py", line 179, in predict_greedy
    h_in, (hn, cn) = self.encode(enc_inputs, src_lens)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/stanza/models/common/seq2seq_model.py", line 119, in encode
    packed_h_in, (hn, cn) = self.encoder(packed_inputs, (self.h0, self.c0))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 574, in forward
    self.check_forward_args(input, hx, batch_sizes)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 528, in check_forward_args
    self.check_hidden_size(hidden[0], expected_hidden_size,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 195, in check_hidden_size
    raise RuntimeError(msg.format(expected_hidden_size, tuple(hx.size())))
RuntimeError: Expected hidden[0] size (2, 5, 100), got (2, 7, 100)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mtap/processing/service.py", line 192, in Process
    result, times, added_indices = self._runner.call_process(request.event_id, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mtap/processing/_runners.py", line 91, in call_process
    raise ProcessingError() from e
mtap.processing._runners.ProcessingError

```

**Environment**
 - OS: MacOS High Sierra
 - Version 10.13.6
 - Python Version 3.8
 - Java Version [e.g. OpenJDK 8.0]

**Comment by benknoll-umn** [comment]
This looks like an issue with Stanford’s Stanza library, which we use for dependency parsing. I’ll look into it.

**Comment by benknoll-umn** [comment]
This is a bug in stanza, you can resolve by changing the method "encode" in your virtualenv/python installation's "site-packages/stanza/models/common/seq2seq_model.py" to the following until they push a fix:

```python
def encode(self, enc_inputs, lens):
        """ Encode source sequence. """
        h0, c0 = self.zero_state(enc_inputs)

        packed_inputs = nn.utils.rnn.pack_padded_sequence(enc_inputs, lens, batch_first=True)
        packed_h_in, (hn, cn) = self.encoder(packed_inputs, (h0, c0))
        h_in, _ = nn.utils.rnn.pad_packed_sequence(packed_h_in, batch_first=True)
        hn = torch.cat((hn[-1], hn[-2]), 1)
        cn = torch.cat((cn[-1], cn[-2]), 1)
        return h_in, (hn, cn)

```

**Comment by polkhovsky** [comment]
Sorry for the delay. I was away for the long weekend.

pip3 show stanza
Name: stanza
Version: 1.1.1
Summary: A Python NLP Library for Many Human Languages, by the Stanford NLP Group
Home-page: https://github.com/stanfordnlp/stanza
Author: Stanford Natural Language Processing Group
Author-email: jebolton@stanford.edu
License: Apache License 2.0
Location: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages
Requires: tqdm, requests, protobuf, numpy, torch
Required-by: biomedicus

**Comment by polkhovsky** [comment]
I updated the function per your instructions and the problem disappeared. Thank you.
