### ISSUE TITLE
Maximum Iterations reached while processing dependency graph.

### ISSUE THREAD

**Issue by polkhovsky** [nlpie/biomedicus#74]
**Describe the bug**
The batch process consistently fails while processing a specific file. I opened the file stanza_selective_parser.py and increased `MAX_ITER = 50000` but that didn't help. 

**Terminal Output**
```
Processor "biomedicus-selective-dependencies" failed while processing event with id: 9456997-182295206.txt
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mtap/processing/_runners.py", line 85, in call_process
    result = self.processor.process(event, p)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mtap/processing/base.py", line 296, in process
    return self.process_document(document, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/biomedicus/dependencies/stanza_selective_parser.py", line 100, in process_document
    raise ValueError(
ValueError: Maximum Iterations reached while processing dependency graph.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mtap/processing/_runners.py", line 85, in call_process
    result = self.processor.process(event, p)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mtap/processing/base.py", line 296, in process
    return self.process_document(document, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/biomedicus/dependencies/stanza_selective_parser.py", line 100, in process_document
    raise ValueError(
ValueError: Maximum Iterations reached while processing dependency graph.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mtap/processing/service.py", line 192, in Process
    result, times, added_indices = self._runner.call_process(request.event_id, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mtap/processing/_runners.py", line 91, in call_process
    raise ProcessingError() from e
mtap.processing._runners.ProcessingError
```

**Environment**
 - OS: MacOS
 - Version 3.0b6
 - Python Version 3.8
 - Java Version  OpenJDK 8.0

**Additional context**
Here's the offending file:
[9456997-182295206.txt](https://github.com/nlpie/biomedicus3/files/5196077/9456997-182295206.txt)

**Comment by benknoll-umn** [comment]
MAX_ITER is just to a prevent a hang due to infinite loops in an unforeseen edge case, which this file probably is. I'll test the file and find out what's causing it.
