### ISSUE TITLE
Hotfix 1.8.4 testing on mimic data breaks

### ISSUE THREAD

**Issue by GregSilverman** [nlpie/biomedicus#80]
Encountered the following error:

```
...
2018-02-08 15:23:45,105 INFO  [[Procesing Pipeline#1 Thread]::] XmiWriter (XmiWriter.java:98) - Writing XMI CAS to location: examples/plaintext/output/1444809.xmi
2018-02-08 15:23:45,110 INFO  [[CollectionReader Thread]::] FilesInDirectoryReader (FilesInDirectoryReader.java:179) - Reading file: 1630671.txt
2018-02-08 15:23:45,183 INFO  [[Procesing Pipeline#1 Thread]::] XmiWriter (XmiWriter.java:98) - Writing XMI CAS to location: examples/plaintext/output/1834026.xmi
2018-02-08 15:23:45,184 INFO  [[CollectionReader Thread]::] FilesInDirectoryReader (FilesInDirectoryReader.java:179) - Reading file: 1477596.txt
2018-02-08 15:23:45,268 INFO  [[Procesing Pipeline#1 Thread]::] XmiWriter (XmiWriter.java:98) - Writing XMI CAS to location: examples/plaintext/output/1832457.xmi
2018-02-08 15:23:45,270 INFO  [[CollectionReader Thread]::] FilesInDirectoryReader (FilesInDirectoryReader.java:179) - Reading file: 1140867.txt
2018-02-08 15:23:45,358 INFO  [[Procesing Pipeline#1 Thread]::] XmiWriter (XmiWriter.java:98) - Writing XMI CAS to location: examples/plaintext/output/1630671.xmi
2018-02-08 15:23:45,361 ERROR [[Procesing Pipeline#1 Thread]::] XmiWriter (XmiWriter.java:104) - Failed on document: {}
2018-02-08 15:23:45,361 ERROR [[Procesing Pipeline#1 Thread]::] PrimitiveAnalysisEngine_impl (PrimitiveAnalysisEngine_impl.java:417) - Exception occurred
org.apache.uima.analysis_engine.AnalysisEngineProcessException
	at edu.umn.biomedicus.uima.xmi.XmiWriter.process(XmiWriter.java:105) ~[biomedicus-uima-1.8.4.jar:?]
	at org.apache.uima.analysis_component.CasAnnotator_ImplBase.process(CasAnnotator_ImplBase.java:56) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385) [uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:308) [uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:269) [uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.processNext(ProcessingUnit.java:893) [uimaj-cpe-2.8.1.jar:2.8.1]
	at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.run(ProcessingUnit.java:575) [uimaj-cpe-2.8.1.jar:2.8.1]
Caused by: org.xml.sax.SAXParseException: Trying to serialize non-XML 1.0 character: , 0x14 at offset 670 in string starting with MICU EAST NPN 0700-[**3288**]

Please see flowsheet for further details.

A&O x3. Denies pain. No C/
	at org.apache.uima.util.XMLSerializer$CharacterValidatingContentHandler.checkForInvalidXmlChars(XMLSerializer.java:374) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.util.XMLSerializer$CharacterValidatingContentHandler.startElement(XMLSerializer.java:275) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.XmiCasSerializer$XmiDocSerializer.startElement(XmiCasSerializer.java:1197) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.XmiCasSerializer$XmiDocSerializer.writeFsOrLists(XmiCasSerializer.java:711) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.XmiCasSerializer$XmiDocSerializer.writeFs(XmiCasSerializer.java:697) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.CasSerializerSupport$CasDocSerializer.encodeFS(CasSerializerSupport.java:1109) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.CasSerializerSupport$CasDocSerializer.encodeQueued(CasSerializerSupport.java:1013) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.XmiCasSerializer$XmiDocSerializer.writeFeatureStructures(XmiCasSerializer.java:563) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.CasSerializerSupport$CasDocSerializer.serialize(CasSerializerSupport.java:439) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.XmiCasSerializer.serialize(XmiCasSerializer.java:415) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.XmiCasSerializer.serialize(XmiCasSerializer.java:327) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.XmiCasSerializer.serialize(XmiCasSerializer.java:295) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.XmiCasSerializer.serialize(XmiCasSerializer.java:248) ~[uimaj-core-2.8.1.jar:2.8.1]
	at edu.umn.biomedicus.uima.xmi.XmiWriter.process(XmiWriter.java:102) ~[biomedicus-uima-1.8.4.jar:?]
	... 6 more
org.apache.uima.analysis_engine.AnalysisEngineProcessException
	at edu.umn.biomedicus.uima.xmi.XmiWriter.process(XmiWriter.java:105)
	at org.apache.uima.analysis_component.CasAnnotator_ImplBase.process(CasAnnotator_ImplBase.java:56)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:308)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:269)
	at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.processNext(ProcessingUnit.java:893)
	at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.run(ProcessingUnit.java:575)
Caused by: org.xml.sax.SAXParseException; Trying to serialize non-XML 1.0 character: , 0x14 at offset 670 in string starting with MICU EAST NPN 0700-[**3288**]

Please see flowsheet for further details.

A&O x3. Denies pain. No C/
	at org.apache.uima.util.XMLSerializer$CharacterValidatingContentHandler.checkForInvalidXmlChars(XMLSerializer.java:374)
	at org.apache.uima.util.XMLSerializer$CharacterValidatingContentHandler.startElement(XMLSerializer.java:275)
	at org.apache.uima.cas.impl.XmiCasSerializer$XmiDocSerializer.startElement(XmiCasSerializer.java:1197)
	at org.apache.uima.cas.impl.XmiCasSerializer$XmiDocSerializer.writeFsOrLists(XmiCasSerializer.java:711)
	at org.apache.uima.cas.impl.XmiCasSerializer$XmiDocSerializer.writeFs(XmiCasSerializer.java:697)
	at org.apache.uima.cas.impl.CasSerializerSupport$CasDocSerializer.encodeFS(CasSerializerSupport.java:1109)
	at org.apache.uima.cas.impl.CasSerializerSupport$CasDocSerializer.encodeQueued(CasSerializerSupport.java:1013)
	at org.apache.uima.cas.impl.XmiCasSerializer$XmiDocSerializer.writeFeatureStructures(XmiCasSerializer.java:563)
	at org.apache.uima.cas.impl.CasSerializerSupport$CasDocSerializer.serialize(CasSerializerSupport.java:439)
	at org.apache.uima.cas.impl.XmiCasSerializer.serialize(XmiCasSerializer.java:415)
	at org.apache.uima.cas.impl.XmiCasSerializer.serialize(XmiCasSerializer.java:327)
	at org.apache.uima.cas.impl.XmiCasSerializer.serialize(XmiCasSerializer.java:295)
	at org.apache.uima.cas.impl.XmiCasSerializer.serialize(XmiCasSerializer.java:248)
	at edu.umn.biomedicus.uima.xmi.XmiWriter.process(XmiWriter.java:102)
	... 6 more
2018-02-08 15:23:45,376 ERROR [[Procesing Pipeline#1 Thread]::] ProcessingUnit (ProcessingUnit.java:2345) - The container XMI Writer returned the following error message: null (Thread Name: [Procesing Pipeline#1 Thread]::)
2018-02-08 15:23:45,377 ERROR [[Procesing Pipeline#1 Thread]::] ProcessingUnit (ProcessingUnit.java:2498) - Thread: [Procesing Pipeline#1 Thread]::, message: null
org.apache.uima.analysis_engine.AnalysisEngineProcessException
	at edu.umn.biomedicus.uima.xmi.XmiWriter.process(XmiWriter.java:105) ~[biomedicus-uima-1.8.4.jar:?]
	at org.apache.uima.analysis_component.CasAnnotator_ImplBase.process(CasAnnotator_ImplBase.java:56) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:308) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:269) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.processNext(ProcessingUnit.java:893) [uimaj-cpe-2.8.1.jar:2.8.1]
	at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.run(ProcessingUnit.java:575) [uimaj-cpe-2.8.1.jar:2.8.1]
Caused by: org.xml.sax.SAXParseException: Trying to serialize non-XML 1.0 character: , 0x14 at offset 670 in string starting with MICU EAST NPN 0700-[**3288**]

Please see flowsheet for further details.

A&O x3. Denies pain. No C/
	at org.apache.uima.util.XMLSerializer$CharacterValidatingContentHandler.checkForInvalidXmlChars(XMLSerializer.java:374) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.util.XMLSerializer$CharacterValidatingContentHandler.startElement(XMLSerializer.java:275) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.XmiCasSerializer$XmiDocSerializer.startElement(XmiCasSerializer.java:1197) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.XmiCasSerializer$XmiDocSerializer.writeFsOrLists(XmiCasSerializer.java:711) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.XmiCasSerializer$XmiDocSerializer.writeFs(XmiCasSerializer.java:697) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.CasSerializerSupport$CasDocSerializer.encodeFS(CasSerializerSupport.java:1109) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.CasSerializerSupport$CasDocSerializer.encodeQueued(CasSerializerSupport.java:1013) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.XmiCasSerializer$XmiDocSerializer.writeFeatureStructures(XmiCasSerializer.java:563) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.CasSerializerSupport$CasDocSerializer.serialize(CasSerializerSupport.java:439) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.XmiCasSerializer.serialize(XmiCasSerializer.java:415) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.XmiCasSerializer.serialize(XmiCasSerializer.java:327) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.XmiCasSerializer.serialize(XmiCasSerializer.java:295) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.XmiCasSerializer.serialize(XmiCasSerializer.java:248) ~[uimaj-core-2.8.1.jar:2.8.1]
	at edu.umn.biomedicus.uima.xmi.XmiWriter.process(XmiWriter.java:102) ~[biomedicus-uima-1.8.4.jar:?]
	... 6 more
2018-02-08 15:23:45,380 ERROR [[Procesing Pipeline#1 Thread]::] SimpleRunCPE$1 (SimpleRunCPE.java:110) - Exception processing a CAS:
org.apache.uima.analysis_engine.AnalysisEngineProcessException
	at edu.umn.biomedicus.uima.xmi.XmiWriter.process(XmiWriter.java:105) ~[biomedicus-uima-1.8.4.jar:?]
	at org.apache.uima.analysis_component.CasAnnotator_ImplBase.process(CasAnnotator_ImplBase.java:56) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:308) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:269) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.processNext(ProcessingUnit.java:893) [uimaj-cpe-2.8.1.jar:2.8.1]
	at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.run(ProcessingUnit.java:575) [uimaj-cpe-2.8.1.jar:2.8.1]
Caused by: org.xml.sax.SAXParseException: Trying to serialize non-XML 1.0 character: , 0x14 at offset 670 in string starting with MICU EAST NPN 0700-[**3288**]

Please see flowsheet for further details.

A&O x3. Denies pain. No C/
	at org.apache.uima.util.XMLSerializer$CharacterValidatingContentHandler.checkForInvalidXmlChars(XMLSerializer.java:374) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.util.XMLSerializer$CharacterValidatingContentHandler.startElement(XMLSerializer.java:275) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.XmiCasSerializer$XmiDocSerializer.startElement(XmiCasSerializer.java:1197) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.XmiCasSerializer$XmiDocSerializer.writeFsOrLists(XmiCasSerializer.java:711) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.XmiCasSerializer$XmiDocSerializer.writeFs(XmiCasSerializer.java:697) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.CasSerializerSupport$CasDocSerializer.encodeFS(CasSerializerSupport.java:1109) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.CasSerializerSupport$CasDocSerializer.encodeQueued(CasSerializerSupport.java:1013) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.XmiCasSerializer$XmiDocSerializer.writeFeatureStructures(XmiCasSerializer.java:563) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.CasSerializerSupport$CasDocSerializer.serialize(CasSerializerSupport.java:439) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.XmiCasSerializer.serialize(XmiCasSerializer.java:415) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.XmiCasSerializer.serialize(XmiCasSerializer.java:327) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.XmiCasSerializer.serialize(XmiCasSerializer.java:295) ~[uimaj-core-2.8.1.jar:2.8.1]
	at org.apache.uima.cas.impl.XmiCasSerializer.serialize(XmiCasSerializer.java:248) ~[uimaj-core-2.8.1.jar:2.8.1]
	at edu.umn.biomedicus.uima.xmi.XmiWriter.process(XmiWriter.java:102) ~[biomedicus-uima-1.8.4.jar:?]
	... 6 more
2018-02-08 15:23:45,394 ERROR [[Procesing Pipeline#1 Thread]::] ProcessingUnit (ProcessingUnit.java:2498) - Thread: [Procesing Pipeline#1 Thread]::, message: Processing exception
java.lang.RuntimeException: Processing exception
	at edu.umn.biomedicus.uima.util.SimpleRunCPE$1.entityProcessComplete(SimpleRunCPE.java:113) ~[biomedicus-uima-1.8.4.jar:?]
	at org.apache.uima.collection.impl.cpm.engine.CPMEngine.callEntityProcessCompleteWithCAS(CPMEngine.java:3473) ~[uimaj-cpe-2.8.1.jar:2.8.1]
	at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.doNotifyListeners(ProcessingUnit.java:1648) ~[uimaj-cpe-2.8.1.jar:2.8.1]
	at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.notifyListeners(ProcessingUnit.java:1590) ~[uimaj-cpe-2.8.1.jar:2.8.1]
	at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.processNext(ProcessingUnit.java:957) [uimaj-cpe-2.8.1.jar:2.8.1]
	at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.run(ProcessingUnit.java:575) [uimaj-cpe-2.8.1.jar:2.8.1]
2018-02-08 15:23:45,396 ERROR [BaseCPMImpl-Thread] SimpleRunCPE$1 (SimpleRunCPE.java:99) - CPE processing was aborted
```

**Comment by GregSilverman** [comment]
Never mind. I am using a new uncleaned set.
