### ISSUE TITLE
Issue when running 

### ISSUE THREAD

**Issue by Mcilie** [nlpie/biomedicus#91]
i get a file not found error for version 2.1.0
	at org.apache.uima.tools.cpm.CpmPanel$1.run(CpmPanel.java:713)
Caused by: org.rocksdb.RocksDBException: While opening a file for sequentially reading: /Users/michaelilie/biomedicus/biomedicus-distribution/target/biomedicus-distribution-2.1.0-SNAPSHOT-release/data/vocabulary/wordsTerms/CURRENT: No such file or directory
	at org.rocksdb.RocksDB.openROnly(Native Method)
	at org.rocksdb.RocksDB.openReadOnly(RocksDB.java:366)
	at org.rocksdb.RocksDB.openReadOnly(RocksDB.java:315)
	at edu.umn.biomedicus.common.dictionary.RocksDbStrings.<init>(RocksDbStrings.java:43)
	... 49 more

2 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at edu.umn.biomedicus.framework.Bootstrapper.biomedicus(Bootstrapper.java:293)
	at edu.umn.biomedicus.framework.Bootstrapper.create(Bootstrapper.java:106)
	at edu.umn.biomedicus.framework.Bootstrapper.create(Bootstrapper.java:120)
	at edu.umn.biomedicus.uima.adapter.GuiceInjector.<init>(GuiceInjector.java:54)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.uima.impl.CustomResourceFactory_impl.produceResource(CustomResourceFactory_impl.java:79)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:279)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:248)
	at org.apache.uima.resource.impl.ResourceManager_impl.registerResource(ResourceManager_impl.java:720)
	at org.apache.uima.resource.impl.ResourceManager_impl.initializeExternalResources(ResourceManager_impl.java:594)
	at org.apache.uima.resource.Resource_ImplBase.initialize(Resource_ImplBase.java:210)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.initialize(AnalysisEngineImplBase.java:157)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initialize(AggregateAnalysisEngine_impl.java:128)
	at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:279)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:331)
	at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:448)
	at org.apache.uima.collection.impl.cpm.container.CPEFactory.produceIntegratedCasProcessor(CPEFactory.java:1085)
	... 9 more
this crashes the application

**Comment by Mcilie** [comment]
this is only a partial log
as the entire error is longer. Something about injections, and other files are not being found

**Comment by benknoll-umn** [comment]
Hello, what data distribution are you using and did you set BIOMEDICUS_HOME or biomedicus.paths.data in the config.yml? Also, what operating system are you running?
